### ISSUE TITLE
error on pip install...

### ISSUE THREAD

**Issue by alec-djinn** [priestc/moneywagon#1]
Something goes wrong when it is looking for README.md...

$ pip install moneywagon

Collecting moneywagon
  Using cached moneywagon-1.0.3.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-cjxtgwol/moneywagon/setup.py", line 9, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-cjxtgwol/moneywagon/setup.py", line 9, in <module>
    
        long_description=open('README.md').read(),
    
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qp/7w5k82s92rncmtd89bsrxw4w0000gn/T/pip-build-cjxtgwol/moneywagon

**Comment by priestc** [comment]
fixed in 1.0.4
